# ======================================#
#   demo --- Configuration Spring Boot  #
#   Environnement: developpement        #
#=======================================#

# Nom de l'application
spring.application.name=demo

# Base de donnees
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_pro
spring.datasource.username=demo_user
spring.datasource.password=demo_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log
logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG

# JWT
jwt.secret=sensante-pro-secret-key-esp-ucad-dakar-2025-minimum-256-bits
jwt.expiration=86400000

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method