# Nom du workflow
name: Pipeline CI/CD complete

# Permissions
permissions:
    contents: read
    packages: write
    actions: read
    security-events: write

# Declenchement
on:
    push:
        branches: [main]

# Variables d'environnement
env:
    REGISTRY: ghcr.io
    IMAGE_TAG: ${{ github.sha }}

# Taches du workflow
jobs:
    #======================#
    # TACHE : Test backend #
    #======================#
    test-backend:
        name: Tests Backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout du code
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

            - name: Installation de java 21
              uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: 'maven'

            - name: Tests
              run: mvn test --no-transfer-progress

            - name: Rapport de tests
              if: always()
              uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
              with:
                name: Rapports de tests
                path: target/surefire-reports/*.xml
                reporter: java-junit

    #======================#
    # TACHE : Build & Push #
    #======================#
    build:
        name: Build & Push Docker image
        runs-on: ubuntu-latest
        needs: test-backend
        steps:
            - name: Checkout du code
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

            - name: Login GHCR
              uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
            
            # BACKEND SPRING BOOT
            - name: Build & Push Backend
              uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
              with:
                context: .
                file: Dockerfile
                push: true
                tags: |
                    ghcr.io/${{ github.repository }}/backend:${{ env.IMAGE_TAG }}
                    ghcr.io/${{ github.repository }}/backend:latest

            # FRONTEND REACT
            - name: Build & Push Frontend
              uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                build-args: |
                    VITE_API_URL=${{ secrets.VITE_API_URL }}
                tags: |
                    ghcr.io/${{ github.repository }}/frontend:${{ env.IMAGE_TAG }}
                    ghcr.io/${{ github.repository }}/frontend:latest

    deploy-staging:
        name: Deployment into the staging environment
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Executer les commandes via SSH
              uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                    cd /srv/sensante-pro/IPDL_v2

                    export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
                    export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                    export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                    export JWT_SECRET=${{ secrets.JWT_SECRET }}
                    export ANTHROPIC_AUTH_TOKEN=${{ secrets.ANTHROPIC_AUTH_TOKEN }}
                    export GITHUB_REPOSITORY=${{ github.repository }}
                    export IMAGE_TAG=${{ github.sha }}

                    docker compose -f docker-compose.prod.yml pull
                    docker compose -f docker-compose.prod.yml up -d